# Site settings
title: nlswale
email: saps.laj@gmail.com
description: everything you need
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nlswale.github.io/" # the base hostname & protocol for your site
twitter_username: sapslaj
github_username:  sapslaj

# Build settings
markdown: kramdown
